// tslint:disable

export const atolls = [
  {
    officialName: 'Thiladhunmathi Uthuruburi',
    commonName: 'Haa Alifu Atoll',
    islands: [
      'Alidhoo (R)',
      'Alidhuffarufinolhu (U)',
      'Baarah (I)',
      'Beenaafushi (Bibeerah) (U)',
      'Berinmadhoo (PR)',
      'Dhapparuhuraa (U)',
      'Dhihdhoo (I)',
      'Dhonakulhi (R)',
      'Filladhoo (I)',
      'Gaamathikulhudhoo (R)',
      'Gallandhoo (U)',
      'Govvaafushi (U)',
      'Hathifushi (I)',
      'Huvahandhoo (U)',
      'Huvarafushi (I)',
      'Ihavandhoo (I)',
      'Innafinolhu (U)',
      "Kan'daalifinolhu (U)",
      'Kelaa (I)',
      'Kudafinolhu (U)',
      'Maafahi (U) (IND)',
      'Maafinolhu (U)',
      'Maarandhoo (I)',
      'Maarandhoofarufinolhu (U)',
      'Madulu (U)',
      'Manafaru (R)',
      'Matheerah (U)',
      'Medhafushi (Medhufinolhu) (U)',
      'Mulhadhoo (I)',
      'Mulidhoo (U)',
      'Muraidhoo (I)',
      'Naridhoo (R)',
      'Thakandhoo (I)',
      'Thuraakunu (I)',
      'Uligamu (I) (H)',
      "Un'gulifinolhu (U)",
      'Utheemu (I)',
      "Van'gaaru (R)",
      'Vashafaru (I)',
      'Velifinolhu (U',
    ],
  },
  {
    officialName: 'Thiladhunmathi Dhekunuburi',
    commonName: 'Haa Dhaalu Atoll',
    islands: [
      'Dhipparufushi (U)',
      'Faridhoo (I)',
      'Fenboahuraa (U)',
      'Finey (I)',
      'Hanimaadhoo (I)',
      'Hirimaradhoo (I)',
      'Hirinaidhoo (U)',
      "Hon'daafushi (PR)",
      "Hon'daidhoo (U) (IND)",
      'Innafushi (U)',
      'Kanamana (U)',
      'Kattalafushi (U)',
      'Keylakunu (U)',
      'Kudafarufasgandu (U)',
      'Kudamuraidhoo (U)',
      'Kulhudhuffushi (I)',
      'Kumundhoo (I)',
      "Kun'burudhoo (I)",
      "Kurin'bee (I)",
      'Maavaidhoo (I)',
      'Makunudhoo (I)',
      'Muiri (R)',
      'Naagoashi (PR)',
      'Naivaadhoo (I)',
      'Nellaidhoo (I)',
      'Neykurendhoo (I)',
      'Nolhivaramu (I)',
      'Nolhivaranfaru (I)',
      'Ruffushi (U)',
      'Theefaridhoo (U) (IND)',
      'Vaikaradhoo (I)',
      'Vaikaramuraidhoo (U) (IND)',
      "Veligan'du (Veligau)(U)",
      'Kuredhigadu (Huskuredhi',
    ],
  },
  {
    officialName: 'Miladhunmadulu Uthuruburi',
    commonName: 'Shaviyani Atoll',
    islands: [
      'Bileiyfahi (I)',
      'Bis alhaahuraa (U)',
      'Boduhuraa (U)',
      'Bolissafaru (U)',
      'Dhigurah (U)',
      'Dholhiyadhoo (PR)',
      'Dholhiyadhookudarah (U)',
      'Dhonvelihuraa (Thahbeyhuraa) (U)',
      'Ekasdhoo (U) (IND)',
      'Eriadhoo (U) (IND)',
      'Farukolhu (PR) (ADF,H)',
      'Feevah (I)',
      'Feydhoo (I)',
      'Firubaidhoo (U) (IND)',
      'Foakaidhoo (I)',
      'Funadhoo (I)',
      'Fushifaru (U)',
      'Gaakoshibi (PR)',
      'Gallaidhoo (U)',
      'Goidhoo (I)',
      'Gonaafarufinolhu (U)',
      'Horubadhoo (Hirubadhoo) (U)',
      'Hurasfaru (U)',
      'Kakaa eriyadhoo (U)',
      "Kan'baalifaru (PR)",
      "Kan'ditheemu(I)",
      'Keekimini (U) (IND)',
      'Komandoo (I)',
      'Kudadhoo (U)',
      'Kudafarufinolhu (U)',
      'Kudalhaimendhoo (U)',
      'Lhaimagu (I)',
      "Maakan'doodhoo (U) (IND)",
      "Maaun'goodhoo (I)",
      'Madidhoo (U) (IND)',
      'Madikurehdhoo (U) (IND)',
      'Mairah (Dhiguvelidhoo) (U)',
      'Maroshi (I)',
      'Mathikomandoo (U)',
      "Medhukun'burudhoo (U) (IND)",
      'Medhurah (U)',
      'Migoodhoo (U)',
      'Milandhoo (I)',
      'Naainfarufinolhu (U)',
      'Naalaahuraa (U)',
      'Nalandhoo (U) (IND)',
      'Narudhoo (I)',
      "Narurin'budhoo (U)",
      'Neyo (U)',
      'Noomaraa (I)',
      "Raggan'duhuraa (U)",
      'Vagaru (PR)',
      'Naainfaru (U)',
    ],
  },
  {
    officialName: 'Miladhunmadulu Dhekunuburi',
    commonName: 'Noonu Atoll',
    islands: [
      "Ban'daidhidhdhoo (U) (IND)",
      'Bodufushi (Ehdhupparu falhu) (U)',
      'Bodulhaimendhoo (U)',
      'Burehifasdhoo (U)',
      'Dheefuram (U)',
      'Dhekenanfaru (U)',
      'Dhelibe ruh elhihuraa (U)',
      'Dhigurah (U)',
      "Dhonaeri kan'doodhoo (U)",
      'Ehdhuffaru mairah (U) (IND)',
      'Ekulhivaru (PR)',
      'Farumuli (U)',
      'Felivaru (U) (IND)',
      'Fohdhipparu (U)',
      'Fohdhoo (I)',
      'Orimasvaru (U)',
      "Goan'bilivaadhoo (U)",
      "Hen'badhoo (I)",
      'Holhudhoo (I)',
      'Holhumeedhoo (U)',
      'Huivani (U)',
      'Hulhuhdhoo (U)',
      "Huvan'dhumaavattaru (PR)",
      "In'guraidhoo (U)",
      'Kaalhugemendhoo (Gemendhoo) (U)',
      'Kafakomandoo (U)',
      'Kalaidhoo (U) (IND)',
      "Kan'dinmaahuraa (U)",
      'Karinma (U)',
      'Karinmavattaru (U) (IND)',
      'Kedhivaru (U)',
      "Ken'dhikulhudhoo (I)",
      'Kudafari (I)',
      'Kudafunafaru (Kudafarumaafaru) (R)',
      'Kudafushi (Ehdhupparufalhu) (U)',
      'Kunnamalei (U)',
      'Kuramaadhoo (U) (IND)',
      'Kuredhivaru (U)',
      'Landhoo (I)',
      'Lhohi (I)',
      'Loafaru (U)',
      'Maafaru (I) (ADF, H)',
      'Maafunafaru (U)',
      'Maakanaafushi (Ehdhupparufalhu) (U)',
      'Maakurehdhoo (U) (IND)',
      'Maalhendhoo (I)',
      'Maavahdhoo (U)',
      'Maavelavaru (PR)',
      'Magoodhoo (I)',
      'Manadhoo (I)',
      'Medhafushi (R)',
      'Medhufaru (R)',
      'Miladhoo (I)',
      'Minaavaru (U) (IND)',
      'Fushivelavaru (U)',
      'Orivaru (U)',
      'Orivarukudarah (Rasgefushi) (U)',
      'Raafushi (U)',
      'Raalhulaakolhu (Raalhugandu) (U)',
      'Randheli (R)',
      "Than'burudhoo (U) (IND)",
      "Than'burudhuffushi (Thanburudhu'faru) (U)",
      'Tholhendhoo (U)',
      "Thoshigan'dukolhu (Eh'dhupparufalhu) (U)",
      'Vavathi (U)',
      'Velidhoo (I)',
      'Vihafarufinolhu (U)',
      'Bomasdhoo(U)',
    ],
  },
  {
    officialName: 'Maalhosmadulu Uthuruburi',
    commonName: 'Raa Atoll',
    islands: [
      'Aarah (U)',
      'Alifushi (I)',
      'Angaagiri (U)',
      "An'golhitheemu (I)",
      'Arilundhoo (U)',
      "Ban'daveri (U)",
      'Bodufarufinolhu (U)',
      "Bodufen maaen'budhoo (U",
      'Bodufushi (U)',
      'Boduhaiykodi (U) (IND)',
      'Boduhuraa (U)',
      'Dheburidheythereyvaadhoo (U) (IND)',
      'Dhekunumaafaru (U)',
      'Dhigali (R)',
      'Dhikkurehdhoo (U)',
      'Dhinnaafushi (U)',
      'Dhoragali (U)',
      'Dhuvaafaru (I)',
      'Dhuvaafaruhuraa (U)',
      "Ethigan'du jehihuraa (U)",
      'Ehthigili (U)',
      'Faarufushi (Fararafushi) (U)',
      'Fainu (I)',
      "Fasgan'dufaru (Husveli) (U)",
      'Fasmendhoo (U)',
      'Fenfushi (U) (IND)',
      'Filaidhoo (U)',
      'Fuggiri (U)',
      'Furaveri (Faruveri) (R)',
      "Gaaun'doodhoo (U)",
      'Giraavaru(U)',
      'Goboshi (U)',
      'Goiymaru (U)',
      'Goyyafaru (U)',
      'Hiboodhoo (U)',
      'Hiraveri (Husveli) (U)',
      'Hulhudhoo (U)',
      'Hulhudhuffaaru (I)',
      'Huruvalhi (U)',
      'Ifuru (U) (IND)',
      "In'guraidhoo (I)",
      'Innamaadhoo (I)',
      "Kan'dholhudoo (U)",
      "Kandhoomeehunge lhaan'bugali (U)",
      "Kan'doogan'du (U)",
      'Kinolhas (I)',
      'Kothaifaru (U)',
      'Kottefaru (U)',
      "Kudafen maaen'boodhoo (U)",
      'Kudafushi (R)',
      'Kudakurathu (U)',
      'Kudalhosgiri (U)',
      'Kudathulhaadhoo (U)',
      'Kukulhudhoo (U)',
      'Kurehdhoo (kolhikurehdhoo) (U)',
      'Kuroshigiri (U)',
      "Lhaan'bugali (U)",
      'Lhohi (U) (IND)',
      "Lin'boakandhoo (U) (IND)",
      "Lun'dhufushi (PR)",
      'Maakurathu (I)',
      "Maamin'gili (R)",
      'Maamunagau (U)',
      'Maamunagaufinolhu (Husveli) (U)',
      'Maanenfushi (PR)',
      'Maashigiri (U)',
      'Madivaafaru (U)',
      'Maduvvari (I)',
      'Mahidhoo (U)',
      'Meedhoo (I)',
      'Meedhupparu(R)',
      'Mullaafushi (Husveli) (U)',
      'Muravandhoo (U)',
      'Neyo (U) (IND)',
      'Rasgetheemu (I)',
      'Rasmaadhoo (I)',
      'Thaavathaa (U)',
      'Ufulandhoo (U)',
      "Un'goofaaru (I)",
      "Un'gulu (U) (IND)",
      'Uthurumaafaru (U)',
      'Vaadhoo (I)',
      'Vaffushi (U)',
      'Vaffushihuraa (U)',
      'Vandhoo (U)',
      'Veyvah (U)',
      "Vilin'gili (U)",
      'Gemana (U)',
      'Orimasfushi (U)',
      'Minaadhoo (U)',
    ],
  },
  {
    officialName: 'Maalhosmadulu Dhekunuburi',
    commonName: 'Baa Atoll',
    islands: [
      'Ahivaffushi (U)',
      'Aidhoo (U) (IND)',
      'Anhenunfushi (U) (IND)',
      'Bathalaa (U)',
      'Boadhaafushifinolhu (U)',
      'Bodufinolhu (U)',
      'Boifushi (U)',
      'Dhakandhoo (U)',
      'Dhandhoo (R)',
      'Dharavandhoo (I) (ADF,H)',
      'Dhashufaruhuraa (U)',
      'Dhigudhefaru (U)',
      "Dhigufaruvinagan'du (R)",
      'Dhonfanu (I)',
      "Dhoogan'dufinolhu (u)",
      'Dhunikolhu (R)',
      "En'boodhoo (U)",
      'Eydhafushi (I)',
      'Fares (R)',
      'Fehendhoo (I)',
      'Finolhas (U)',
      'Fonimagoodhoo (R)',
      'Fulhadhoo (I)',
      'Funadhoo (U)',
      "Gaagan'dufaruhuraa (U)",
      "Gaavilin'gili (U)",
      'Gemendhoo (U)',
      'Goidhoo (I)',
      'Hanifaru (U)',
      'Hanifaruhuraa (U)',
      'Hibalhidhoo (U)',
      'Hirundhoo (R)',
      'Hithaadhoo (I)',
      'Horubadhoo (R)',
      'Hulhudhoo (U)',
      'Maaddoo Hulhudhoo (U)',
      'Innafushi (R)',
      'Kamadhoo (I)',
      'Kanufusheegaathufinolhu (U)',
      'Kanufushi (R)',
      'Kashidhoo (U) (IND)',
      'Kashidhuffarufinolhu (U)',
      'Kendhoo (I)',
      'Keyodhoo (U)',
      'Kihaadhoo (I)',
      'Kihaadhuffaru (R)',
      'Kihavah huravalhi (R)',
      'Kudadhoo (U) (IND)',
      'Kudarikilu (I)',
      'Kunfunadhoo (R)',
      "Lan'daagiraavaru (R)",
      'Maaddoo (U)',
      'Maalhos (I)',
      'Maamaduvvari (U)',
      'Maarikilu (U) (IND)',
      'Madhirivaadhoo (U)',
      'Mathifaru (U)',
      'Medhufinolhu gaathufinolhu (U)',
      'Mendhoo (U)',
      'Milaidhoo (R)',
      'Miriandhoo (U)',
      'Muhdhoo (R)',
      'Muthaafushi (U)',
      'Nelivarufinolhu(U)',
      'Nibiligaa (U)',
      'Olhugiri (U)',
      'Thiladhoo (U)',
      'Thulhaadhoo (I)',
      'Ufuligiri (U)',
      "Un'doodhoo (U) (IND)",
      'Vakkaru (PR)',
      'Velavaru (U)',
      'Veyofushi (U)',
      'Vinaneiyfaruhuraa (U)',
      'Voavah (R)',
      'Huraafaru (Finolhu) (R)',
      "An'gaafaru (R)",
      'Bathalaa huraa (U)',
      "Vandhuh'maafaru finolhu (U)",
      'Maafusheefinolhu',
      'Finolhufaru (U)',
    ],
  },
  {
    officialName: 'Faadhippolhu',
    commonName: 'Lhaviyani Atoll',
    islands: [
      'Aligaa (U) (IND)',
      "Boamandhipparu huraagan'du (U)",
      'Bodufinolhu (U)',
      'Bodugaahuraa (Bodufaahuraa) (U)',
      'Dhashugirifinolhu (U)',
      'Dheruffinolhu (U)',
      'Dhihdhoo (Ookolhudhihdhoo) (U)',
      'Dhiffushi (Dhiffushimaadhoo) (U)',
      "Dhirun'baahuraa",
      'Faadhoo (U)',
      "Faadhoohuraagan'du (U)",
      'Fainu aadhanhuraa (U)',
      'Fehigili (U)',
      'Felivaru (U) (IND)',
      'Fushifaru (U)',
      'Gaaerifaru (U) (IND)',
      'Govvaafushi (U)',
      'Hinnavaru (I)',
      'Hiriyaadhoo (U)',
      'Hudhufushi (PR)',
      'Huravalhi (R)',
      'Innahuraa (U)',
      'Kalhumanjehuraa (U)',
      'Kanifushi (R)',
      'Kanuhuraa (R)',
      'Komandoo (R)',
      'Kudadhoo (U)',
      'Kurehdhoo (R)',
      'Kurendhoo (I)',
      'Lhohi (U) IND)',
      'Lhossalafushi (U)',
      'Maabinhuraaa (U)',
      'Maafilaafushi (I)',
      'Maakoa (U)',
      'Madhiriguraidhoo (R)',
      'Madivaru (U)',
      'Maduvvari (U) (IND)',
      'Maidhoo (U)',
      'Mas leggihuraa (U)',
      'Medha adihuraa (U)',
      'Medhafushi (U)',
      'Meedhaahuraa (U)',
      'Meyyafushi (U)',
      'Naifaru (I)',
      'Olhuvelifushi (I)',
      'Ookolhufinolhu (U)',
      'Rathuruh-huraa (U)',
      'Sehlhifushi (U)',
      'Thilamaafushi (U)',
      'Varihuraa (U)',
      'Vavvaru (U)',
      "Veligan'du (U)",
      'Veyvah (U)',
      'Vihafarufinolhu (U)',
    ],
  },
  {
    officialName: 'Male Atholhu',
    commonName: 'Kaafu Atoll',
    islands: [
      'Aarah (U)',
      'Akirifushi (R)',
      'Asdhoo (R)',
      'Baros (R)',
      'Biyaadhoo (R)',
      "Boduban'dos (R)",
      'Bodufinolhu (R)',
      'Boduhithi (R)',
      'Boduhuraa (R)',
      'Bolifushi (R)',
      'Dhiffushi (I)',
      'Dhigufinolhu (R)',
      'Dhoonidhoo (U)',
      "En'boodhoo (R)",
      "En'boodhoofinolhu (R)",
      'Eriadhoo (R)',
      'Erruh-huraa (R)',
      'Farukolhufushi (R)',
      'Feydhoofinolhu (R)',
      'Fihaalhohi (R)',
      'Fonadhoo (U)',
      'Furanafushi (R)',
      'Gaafaru (I)',
      "Gaagan'du (Kudahuraa) (U) (IND)",
      'Gashurifinolhu (R)',
      'Giraavaru (R)',
      'Girifushi (U)',
      'Gulhi (I)',
      'Gulhigaathuhuraa (R)',
      'Guraidhoo (I)',
      "Helen'geli (R)",
      'Henbadhoo (R)',
      'Hinmafushi (I)',
      'Hulhule (U) (AIE, H)',
      "Hulhumale' (I)",
      'Huraa (I)',
      'Ihuru (R)',
      'Kaashidhoo (I)',
      'Kagi (R)',
      'Kalhuhuraa (U)',
      "Kan'doomaafushi (R)",
      "Kan'duoiygiri (U) (IND)",
      'Kanifinolhu (R)',
      'Kanuoiyhuraa (R)',
      'Kohdhipparu (R)',
      "Kudaban'dos (R)",
      'Kudafinolhu (R)',
      'Kudahithi (R)',
      'Kudahuraa (R)',
      'Lankanfinolhu (R)',
      'Lankanfushi (R)',
      'Lhohifushi (R)',
      'Lhosfushi (U)',
      'Maadhoo (R)',
      'Maafushi (I)',
      'Madivaru (R)',
      'Mahaana elhihuraa (R)',
      'Maifalhuhuraa (U)',
      'Makundhoo (R)',
      'Makunufushi (R)',
      "Male'(I)[H]",
      'Maniyafushi (U) [IND]',
      'Medhufinolhu (R)',
      'Meerufenfushi (R)',
      'Nakahchaafushi (R)',
      "Olhigan'dufinolhu (U)",
      'Olhuhali (R)',
      'Olhuveli (R)',
      'Rannaalhi (R)',
      'Rasfari (U)',
      "Than'burudhoo (R)",
      'Thilafushi (IND)',
      'Thulhaagiri (R)',
      'Thulusdhoo (I)',
      "Huraagan'du (U)",
      "Thun'bafushi (U) (IND)",
      'Vaadhoo (R)',
      'Vaagali (R)',
      'Vabbinfaru (R)',
      'Vabboahuraa (U) (IRD)',
      'Vammaafushi (U)',
      'Velassaru(R)',
      "Veligan'duhuraa (R)",
      'Vihamanaafushi (R)',
      "Vilin'gili mathidhahuraa (R)",
      'Vilingili (I)',
      'Vilivaru (Viligilivaru) (R)',
      'Ziyaaraiyfushi (R)',
      'Udhafinolhu (Aanugandufinolh) (R)',
      'Tholhimaraa huraa (R)',
      'Dhonfushi (R)',
      'Kanbaashaa (R)',
      'Nashvilu (R)',
      'Hastheem (R)',
      'Maaranfushi (R)',
      'Bodubis (U)',
      'Kudabis (U)',
      "Kohdhipparu fi',nolhu (U)",
      'Ithaafinolhu',
    ],
  },
  {
    officialName: 'Ari Atholhu Uthuruburi',
    commonName: 'Alifu Alifu Atoll',
    islands: [
      'Alikoirah (R)',
      'Bathalaa (R)',
      'Bodufolhudhoo (I)',
      'Ellaidhoo (R)',
      'Etheremadivaru (R)',
      'Feridhoo (I)',
      'Fesdhoo (R)',
      'Fusfinolhu (U)',
      'Fushi (U)',
      "Gaagan'du (U)",
      'Gaathafushi (R)',
      'Gangehi (R)',
      'Halaveli (R)',
      'Himendhoo (I)',
      "Kan'dholhudoo (R)",
      'Kudafolhudhoo (R)',
      'Kuramathi (R)',
      'Maagau (R)',
      'Maalhos (I)',
      'Maayafushi (R)',
      'Madivaru (R)',
      'Madivarufinolhu (U)',
      'Madoogali (R)',
      'Mathivereefinolhu (R)',
      'Mathiveri (I)',
      'Mushimasmigili (R)',
      'Rasdhoo (I)',
      'Thoddoo (I)',
      'Ukulhas(I)',
      'Velidhoo (R)',
      "Veligan'du (R)",
      'Vihamaafaru (U) (IND)',
      'Dhinnolhufinolhu (U)',
    ],
  },
  {
    officialName: 'Ari Atholhu Dhekunuburi',
    commonName: 'Alifu Dhaalu Atoll',
    islands: [
      'Angaagau (R)',
      'Ariyadhoo (U)',
      'Athurugau (R)',
      'Bodufinolhu (R)',
      'Bodukaashihuraa (R)',
      'Bulhalohi (Bulhalafushi) (U)',
      "Dhan'gethi (I)",
      'Dhihdhoo (I)',
      'Dhihdhoofinolhu (R)',
      'Dhiffushi (R)',
      'Dhiggiri (U)',
      'Dhigurah (I)',
      "En'boodhoo (U)",
      'Fenfushi (I)',
      'Hangnaameedhoo (I)',
      'Heenfaru (R)',
      'Hiyafushi (U)',
      'Hukurudhoo (U) (IND)',
      'Hurasdhoo (U)',
      'Huruelhi (R)',
      'Huvahendhoo (R)',
      'Innafushi (R)',
      "Kalhahan'dhihuraa (U)",
      'Kudadhoo (U)',
      'Kudarah (R)',
      "Kun'burudhoo (I)",
      'Lonuboi (U)',
      'Maafushivaru (R)',
      "Maamin'gili (I) [ADF]",
      'Machchafushi (R)',
      'Mahibadhoo (I)',
      'Mandhoo (I)',
      'Mirihi (R)',
      'Moofushi (R)',
      'Nalaguraidhoo (R)',
      'Omadhoo (I)',
      'Rangaleefinolhu (R)',
      'Rangali(R)',
      'Theluveligaa (U)',
      'Tholhifushi (R)',
      "Thun'dufushi (R)",
      'Vakarufalhi (R)',
      'Vilamendhoo (R)',
      "Vilin'gilivaru (R)",
      'Rahdhiggaa (R)',
      'Finolhu (Aafinolhu) (U)',
      'Athulivaru finolhu (U)',
    ],
  },
  {
    officialName: 'Felidhe Atholhu',
    commonName: 'Vaavu Atoll',
    islands: [
      'Aarah (R)',
      'Alimathaa (R)',
      'Anbaraa (R)',
      'Bodumohoraa (U)',
      'Dhiggiri (R)',
      'Felidhoo (I)',
      'Fohtheyobodufushi (R)',
      'Fulidhoo (I)',
      "Hin'gaakulheefinolhu (U)",
      'Hulhidhoo (U)',
      'Keyodhoo (I)',
      'Kuda anbaraa (U)',
      'Kunaavashi (R)',
      'Rakeedhoo (I)',
      'Ruh hurihuraa (U)',
      'Thinadhoo (I)',
      "Thun'duhuraa (U)",
      'Vashugiri (U)',
      'Vattaru (U)',
      "Rah'gandu (U)",
      'Hurahufinolhu (U)',
    ],
  },
  {
    officialName: 'Mulaku Atholhu',
    commonName: 'Meemu Atoll',
    islands: [
      'Boahuraa (R)',
      'Dhekunuboduveli (R)',
      'Dhiggaru (I)',
      "Dhihthun'di (U)",
      'Erruh-huraa (U)',
      'Fenfuraaveli (U) (IND)',
      'Gaakurali (U) (IND)',
      'Gasveli (R)',
      'Gongalihuraa (U)',
      'Hakuraahuraa (R)',
      'Hudhuveli (U)',
      'Hurasveli (U)',
      'Kekuraalhuveli (R)',
      'Kolhufushi(I)',
      'Kuda usfushi (R)',
      "Kuradhigan'du (U)",
      'Maa usfushi (R)',
      'Maahuraa (U)',
      'Maalhaveli (U)',
      'Madifushi (U)',
      'Maduvvari (I)',
      'Medhufushi (R)',
      'Mulah (I)',
      'Muli (I)',
      'Naalaafushi (I)',
      "Raaban'dhihuraa (Raabandhi) (Fenboafinolhu) (U)",
      'Raiymandhoo (I)',
      'Seedheehuraa (U)',
      "Seedheehuraa veligan'du (U)",
      'Thuvaru (U) (IND)',
      'Uthuruboduveli (R)',
      'Uthurugaseveli (R)',
      'Veyvah (I)',
    ],
  },
  {
    officialName: 'Nilandhe Atholhu Uthuruburi',
    commonName: 'Faafu Atoll',
    islands: [
      'Adhangau (U)',
      'Bileiydhoo (I)',
      "Dharan'boodhoo (I)",
      'Dhiguvarufinolhu (U)',
      "En'bulufushi (U)",
      'Faanumaahuraa (U)',
      'Feeali (I)',
      'Filitheyo (R)',
      'Himithi (R)',
      'Jinnathugau (U)',
      "Kan'dumoonufushi (U)",
      'Maafushi (R)',
      'Madivaruhuraa (U)',
      'Magoodhoo (I)',
      'Magoodhoo bodufinolhu (U)',
      'Makunueri (U)',
      'Minimasgali (R)',
      'Nilandhoo (I)',
      "Vilin'gilvarufinolhu (U)",
    ],
  },
  {
    officialName: 'Nilandhe Atholhu Dhekunuburi',
    commonName: 'Dhaalu Atoll',
    islands: [
      'Ayyakaloahuraa (U)',
      "Ban'didhoo (I)",
      'Bulhalafushi (U)',
      'Dhebaidhoo (U)',
      'Dhoores (R)',
      "En'boodhoofushi (R)",
      'Faandhoo (R)',
      'Fenfushi (U)',
      'Fenmeeruhuraa (U)',
      'Gemendhoo (U)',
      'Hiriyafushi (R)',
      'Hudhufusheefinolhu (U)',
      'Hulhudheli (I)',
      'Hulhuvehi (U)',
      'Issari (U)',
      "Kan'dinmaa (R)",
      'Kanneiyfaru (U)',
      "Kedhigan'du (R)",
      'Kiraidhoo (U)',
      'Kudahuvadhoo (I) (ADF, H)',
      'Lhohi (U) (IND)',
      'Maadheli (U) (IND)',
      "Maaen'boodhoo (I)",
      'Maafushi (R)',
      'Maagau (R)',
      'Maalefaru (U)',
      'Meedhoo (I)',
      'Meedhuffushi (R)',
      'Minimasgali (U)',
      'Olhufushi (U)',
      'Olhuveli (R)',
      "Rin'budhoo (I)",
      "Thaban'lhaidhoo (U)",
      'Thilabolhufushi (U)',
      'Thinhuraa (U)',
      'Uhdhoo (U) (IND)',
      'Vaanee (I)',
      'Valla (U)',
      'Vallalhohi (U)',
      'Velavaru (R)',
      'Vommuli (R)',
      'Aluvifushi (U)',
      'Angalhaidhoo (U)',
      'Aarah (Sarakafushi) (U)',
      'Boarikifinolhu',
    ],
  },
  {
    officialName: 'Kolhumadulu',
    commonName: 'Thaa Atoll',
    islands: [
      'Bodufinolhu (U)',
      'Bodurehaa (U)',
      'Burunee (I)',
      'Dhiffushi (U)',
      'Dhiyamigili (I)',
      'Dhonanfushi (U)',
      'Dhururehaa (U)',
      'Ekuruffushi (U)',
      'Elaa (R)',
      'Fenfushi (U)',
      'Fenmeerufushi (U)',
      'Fondhoo (U)',
      'Fonidhaani (U)',
      'Funaddu (U) (IND)',
      "Fushi (Van'badhifushi) (U)",
      'Gaadhiffushi (I)',
      'Gaalee (U)',
      'Gaathurehaa (U)',
      'Guraidhoo (I)',
      'Hathifushi (U)',
      "Hikan'dhihohi (U)",
      'Hirilandhoo (I)',
      'Hiriyanfushi (U)',
      "Hon'delifushi (U)",
      'Hulhiyanfushi (U)',
      'Kaaddoo (U)',
      'Kafidhoo (U)',
      'Kakolhas (U) (IND)',
      'Kalhufahalafushi (PR)',
      "Kan'doodhoo (I)",
      "Kan'dufushi (U)",
      'Kani (U)',
      'Kanimeedhoo (U)',
      "Kin'bidhoo (I)",
      'Kolafushi (U)',
      'Kolhufushi (U)',
      'Kudadhoo (U)',
      'Kudakaaddoo (U)',
      "Kudakin'bidhoo (U)",
      "Kuran'dhuvaru (U)",
      'Kuredhifushi (U)',
      'Lhavaddoo (R)',
      'Maagulhi (U)',
      'Maalefushi (R)',
      'Madifushi (I)',
      'Mathidhoo (U)',
      'Medhafushi (U)',
      'Olhudhiyafushi (U)',
      'Olhufushi (U)',
      'Olhufushifinolhu (U)',
      'Olhugiri (R)',
      'Omadhoo (I)',
      'Rihaamaafushi (U)',
      'Ruhthibirah (R)',
      'Thimarafushi (I) [ADF,H]',
      'Ufuriyaa (U)',
      'Usfushi (U)',
      'Vanbadhi (U)',
      'Vandhoo (I)',
      'Veymandoo (I)',
      'Vilufushi (I)',
      'Kalhudheyfushi (R)',
    ],
  },
  {
    officialName: 'Hahdhunmathi',
    commonName: 'Laamu Atoll',
    islands: [
      'Aarahaa (U)',
      'Athahendha (U)',
      'Baresdhoo (R)',
      'Bodu mungnafushi (U)',
      'Bodufenrahaa (U)',
      'Bodufinolhu (R)',
      'Boduhuraa (Maavashu falhuthere) (R)',
      'Bodumaabulhali (U)',
      'Bodumahigulhi (U)',
      'Bokaiyfushi (U)',
      'Burrahaa (U)',
      "Dhan'bidhoo (I)",
      'Dhonberahaa (U)',
      'Enberahaa (U)',
      'Fares (R)',
      'Fenboarahaa (U)',
      'Fenboahuraa (Isdhoo falhuthere)(U)',
      'Fonadhoo (I)',
      'Fonagaadhoo (U) (IND)',
      'Fushi (U)',
      'Gaadhoo (U)',
      'Gan (I)',
      "Gahagan'dufinolhu (R)",
      'Guraidhoo (U)',
      'Haiythoshi (U)',
      'Hanhushi (U)',
      'Hendha (U)',
      "Hikan'dhirahaa (U)",
      'Hithadhoo (I)',
      'Holhurahaa (U)',
      'Hulhimendhoo (U)',
      'Hulhiyandhoo (U)',
      'Hulhisdhoo (U)',
      'Boduhuraa (Huraa) (Fonadhoo falhuthere) (U)',
      'Isdhoo (I)',
      'Kahdhoo (U) (ADE, H)',
      'Kalhaidhoo (I)',
      'Kalhurahaa (U)',
      'Kandaru (U) (IND)',
      'Kanuhuraa (U)',
      'Kashidhoo (U)',
      'Kokurahaa (U)',
      'Kuda munyafushi (U)',
      'Kudafares (R)',
      'Kudafenrehaa (U)',
      'Kudafushi (U)',
      'Kudamaabulhali (U)',
      'Kudarah (U)',
      'Kudaveshi (U)',
      'Kunahandhoo (I)',
      'Kuredhirehaa (U)',
      'Maabaidhoo (I)',
      'Maafushi (U)',
      'Maakalhuveli (U)',
      'Maamendhoo (I)',
      'Maandhoo(U) (IND)',
      'Maavah (I)',
      'Maaveshi (U)',
      'Mahakanfushi (R)',
      "Medhu vinagan'du (U)",
      'Mendhoo (U) (IND)',
      'Mundoo (I)',
      'Olhutholhu (U)',
      'Olhuveli (R)',
      'Rahaa (U)',
      'Thathunrahaa (U)',
      "Thun'buri (U)",
      "Uthuru vinagan'du (U)",
      'Uvadhevifushi (PR)',
      'Vadinolhu (R)',
      "Veligan'dufinolhu (U)",
      "Dhekunuvinagan'du (U)",
    ],
  },
  {
    officialName: 'Huvadhu Atholhu Uthuruburi',
    commonName: 'Gaafu Alifu Atoll',
    islands: [
      'Araigaththaa (U)',
      'Baavanadhoo (U)',
      'Bakeththaa (R)',
      'Beyrumauddoo (U)',
      'Bihurehaa (U)',
      'Boadduvaa (Boaddoo)(U)',
      'Bodufuttaa (Bodehutta) (U)',
      "Bodubon'deyyaa (U)",
      'Bodufinolhu (U)',
      'Boduhuraa (U)',
      'Dhaandhoo (I)',
      'Dhevvaamaagala (U)',
      'Dhevvadhoo (I)',
      'Dhevvalaabadhoo (U)',
      'Dhigudhoo (U)',
      'Dhigurah (R)',
      'Dhiyadhoo (I)',
      'Falhumaafushi (R)',
      'Falhuverrahaa (U)',
      'Fulhadhoo (Faruhullhehdhoo) (U)',
      'Fenehutta (U)',
      "Fulan'gi (U)",
      'Funadhoo (U)',
      'Funadhooviligillaa (U)',
      'Funamauddaa (Funamauddoo) (R)',
      'Galandhoo (Galamedhuvaa) (U)',
      'Gemanafushi (I)',
      "Han'dahaa (R)",
      'Hinaamaagalaa (R)',
      'Hirihuttaa (Hirufushi) (R)',
      'Hithaadhoo (U)',
      'Hithaadhoogalaa (U)',
      'Hulhimendhoo (U)',
      'Hurendhoo (U)',
      'Idhimaa (U)',
      'Innarehaa (U)',
      'Kalhehuttaa (U)',
      'Kaludirehaa (U)',
      "Kan'duhulhudhoo (I)",
      "Kan'duvilin'gili (U)",
      'Kendheraa (U) (IND)',
      'Kerehdhoo (R)',
      'Kisserahaa (U)',
      'Kodagehuttaa (U)',
      'Kodahuttaa (U)',
      'Kodeymatheelaabadhoo (R)',
      "Kodeyvilin'gili (U)",
      'Kolamaafushi (I)',
      "Kon'dey (I)",
      'Kooddoo (U) (IND)',
      'Kudalafari (U)',
      'Lhossaa (U)',
      'Hagevilla (U)',
      'Maafehelaa (U)',
      'Maagihuttaa (maagefutta) (U)',
      'Maakanaarataa (U)',
      'Maamendhoo (I)',
      'Maamutaa (R)',
      'Maarandhoo (R)',
      'Maarehaa (U)',
      'Mahahdhoo (R)',
      'Mahthidhoo (Falhukoduratta) (Kodafutta) (U)',
      'Mahthurehaa (U)',
      'Matu (U)',
      'Medharehaa (U)',
      'Medhehuttaa (U)',
      'Medhuburiyaa (U)',
      'Melaimu (Melaimaa) (U)',
      'Meradhoo (R)',
      'Minimessa (U)',
      'Munandhuvaa (PR)',
      'Nilandhoo (I)',
      'Odagallaa (U)',
      'Raaverrehaa (U) (IND)',
      "Vilin'gili (I)",
      'Vodamulaa (R)',
      'Ribidhoo (Ribidhuvaa) (U)',
      'Baberahutta',
      'Villigalaa (U)',
      "Kun'bumaafushi (U)",
      'Kudhebondeyyaa (U)',
      'Hagedhoo (U)',
    ],
  },
  {
    officialName: 'Huvadhu Atholhu Dhekunuburi',
    commonName: 'Thaa Atoll',
    islands: [
      'Baulhagallaa (U)',
      'Bodehutta (near nadella) (U)',
      'Boduhuttaa (R)',
      'Bodurehaa (U)',
      'Dekaanbaa (U)',
      'Dherukurehaa (U)',
      'Dhigelaabadhuvaa (Dhigulaabaidhoo) (U)',
      'Dhigurehaa (U)',
      'Dhoonirehaa (Farehu falhuthere) (U)',
      'Dhoonirehaa (near Maavarulu) (U) (IND)',
      'Ehivakaa (U)',
      'Ekelondaa (U)',
      'Farehulhedhoo (Farehulhudhoo) (U)',
      'Faresmaathodaa (I)',
      'Farukolhuhuttaa (R)',
      'Femunaidhoo (U)',
      'Fenevenehuttaa (U)',
      'Fiyoari (I)',
      'Gahdhoo (I)',
      'Velagalaa (Gahevelagalaa) (U)',
      'Gan (U)',
      'Gazeeraa (R)',
      'Golhaallaa (U) (IND)',
      'Gosi (U)',
      'Havoddaa (R)',
      'Havodigalaa (U)',
      'Hevaahulhadhoo (U)',
      "Hoan'dehdoo (I)",
      'Hoothodeyaa (U) (IRD)',
      'Hulhuvaarulaa (Hulhuvaarulu) (U) (IND)',
      "Hunigon'direhaa (U)",
      'Kaadehdhoo (U) (ADH, H)',
      'Kaalhehuttaa - fiyoari falhuthere (U)',
      'Kaalhehuttaa - Farehu falhuthere (U)',
      'Kaashidhoo (PR)',
      'Kaashihulhudhoo (U) (IND)',
      'Kadevaareha (U)',
      'Kudhefalaa (U)',
      'Kafena (U)',
      'Kalhahigillaa (U)',
      'Kalhahuttaa (U)',
      'Kalhehamalaa (U)',
      'Kanandhuvaa (U)',
      "Kan'dahalagalaa (U)",
      'Kannigillaa (U)',
      'Keleihuttaa (U)',
      'Keramihthaa (U) (IND)',
      'Keyhuvadhoo (U)',
      'Kodaanahutta (U)',
      'Kodahutigalaa, Maahutigalaa, Maaodagalaa (U) (IRD)',
      'Kodedhoo (U)',
      'Kodegalaa (U)',
      'Koderataa (U)',
      'Konottaa (R)',
      'Kudhehulhehdhoo (U)',
      'Kudhelifadhoo (U)',
      'Kudhemaaneidhoo (U)',
      'Kudherataa (U)',
      'Laihaa (U)',
      'Lonudhoo (U)',
      'Lonudhoohuttaa (R)',
      'Maaehivakaa (U)',
      'Maagalaa (U)',
      "Maagon'derehaa (U)",
      'Maallaarehaa (U)',
      'Maarehaa (Farehu falhuthere) (U)',
      'Maavaarulu (U)',
      'Maavahdhuva (U) [ADF,H]',
      'Madaveli (I)',
      'Maguhdhuvaa (R)',
      'Mathaidhuvaa (U)',
      'Mathihutta (U)',
      'Mathikeranahuttaa (U)',
      'Meehunthibenehuttaa (U)',
      'Menthandhuvaa (U) (IND)',
      'Meregihutaa (U)',
      'Meyragillaa (U)',
      'Bodehutta (Maguhdhoo falhu theere) (U)',
      'Mudhimaahutta (U)',
      'Nadellaa (I)',
      'Odagallaa (PR)',
      'Olhimuttaa (U)',
      'Olhurataa (U)',
      'Rahadhuvaa (U)',
      'Rathafandhoo (I)',
      'Thelehuttaa (U)',
      'Thinadhoo (I)',
      'Thinahuttaa (U)',
      'Uhehuttaa (U)',
      'Ukurihuttaa (U)',
      'Ulegalaa (U)',
      'Vaadhoo (I)',
      'Vaireyaadhuvaa (U)',
      'Vatavarrehaa (R)',
      'Veraaviligillaa (U)',
      "Vilin'gillaa (U)",
      'Rondaadhuvaa (U)',
      'Hakandhoo',
      'Hadaadhoo',
      'Haveyyarataa',
      'Haadhuvaa',
      'Raabadaafehiratta',
      'Kaafarataa',
      'Kandahdhoo',
      'Kalherehaa',
      'Kudhehaadhuvaa',
      'Kudhebeerahutta',
      'Kudhemathaidhuvaa',
      'Athihuttaa',
      'Aakiraahuttaa',
      'Ekurukaarataa',
      'Maarehaa (Nadalla kairi)',
      "Fare'dhoo",
      'Faahuttaa',
      'Faanahuttaa',
      'Fereythavilligilla',
      "Dhate'keraanahutta",
      "Dhate'mulaidhoo",
      'Dhinmanaa',
      'Lifadhoo',
      'Dhiyanigilla',
      'Oinigilla (U)',
      'Dhoonirehaa (near Nadella) (U)',
      'Kurikeymaahutta',
      'Faathiyehutta (U) (IRD)',
    ],
  },
  {
    officialName: 'Fuvahmulah',
    commonName: 'Gnaviyani Atoll',
    islands: ['Fuvahmulah (I) (ADF,H)'],
  },
  {
    officialName: 'Addu Atholhu',
    commonName: 'Seenu Atoll',
    islands: [
      'Aboohuraa (U)',
      'Bedhey aurah (U)',
      'Boduhajara (U)',
      "Dheeron'di (U)",
      'Dhigiheraa (U)',
      'Fathikedeheragadu (U)',
      'Feydhoo (I)',
      'Gan (U) (AIE,H)',
      "Gauken'di (U)",
      'Geskalhaheraa (R)',
      'Gomahera (R)',
      'Hankede (PR)',
      'Herethere (R)',
      'Hikahera (U)',
      'Hithadhoo (I)',
      'Hulhudhoo (I)',
      "Kan'dihera gan'du (U)",
      'Koahera (U)',
      'Ismehelahera (R)',
      "Kodadhihera gan'du (U)",
      'Kudamaahera (U)',
      'Maahera (U)',
      'Maradhoo (I)',
      'Maradhoofeydhoo (I)',
      'Meedhoo (I)',
      'Mulikede (R)',
      'Savaaheli (R)',
      "Vilin'gili (R)",
      'Hasanbeaarah (U)',
      'Kudhehera (U)',
      'Kudahajara (U)',
      'Kedevaahera (U)',
    ],
  },
];
