export const islands: string[] = [
  'Alifushi',
  'Angolhitheemu',
  'Fainu',
  'Hulhudhuffaaru',
  'Inguraidhoo',
  'Innamaadhoo',
  'Dhuvaafaru',
  'Kinolhas',
  'Maakurathu',
  'Maduvvaree',
  'Meedhoo',
  'Rasgetheemu',
  'Rasmaadhoo',
  'Ungoofaaru (capital of Raa Atoll)',
  'Vaadhoo',
];
