import { promisify } from 'bluebird';
import { getLastCommit } from 'git-last-commit';
import { minify } from 'html-minifier';

const lastCommit = promisify(getLastCommit);

const style = `<head><style>
body{
	margin: 2% 10%;
}
*{
	line-height: 21px;
}
table, td, th {
    border: 1px solid #ddd;
    text-align: left;
}
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 15px;
}
code {
    border: thin solid #00d47c;
    padding: 1px 4px;
    background-color: #b6ffe1;
}
h3 code {
    background-color: yellow;
}
</style></head>`;

export async function getInitDocContent() {
  const commit: any = await lastCommit();
  const minifiedCss = minify(style, { minifyCSS: true }) + '\n\n';
  return (
    minifiedCss +
    `# Database Schema Docs

This file is automatically generated while built on commit [\`${
      commit.shortHash
    }\`](http://192.168.1.55/vajahath/miwago-backend/tree/${
      commit.hash
    })<br>at \`${new Date().toString()}\`.

---

## Tables

Miwago has the following schema structure.
`
  );
}
